# **Next Word Prediction Project**

### Import required libraries

In [ ]:
import numpy as np
import tensorflow as tf

#### Taking some text data

In [ ]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here.
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.singhbhupendra@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.singhbhupendra1208@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan,
you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.singhbhupendra@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee.
So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements,
 I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([faqs])

In [ ]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'for': 14,
 'all': 15,
 'sessions': 16,
 'in': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'session': 33,
 'our': 34,
 'paid': 35,
 'join': 36,
 'able': 37,
 'your': 38,
 'website': 39,
 'placement': 40,
 'fee': 41,
 'monthly': 42,
 'month': 43,
 'not': 44,
 'get': 45,
 'yes': 46,
 'once': 47,
 'past': 48,
 'feb': 49,
 'assistance': 50,
 'data': 51,
 '7': 52,
 '5600': 53,
 'are': 54,
 'watch': 55,
 'by': 56,
 'mail': 57,
 'from': 58,
 'contact': 59,
 'us': 60,
 'at': 61,
 'or': 62,
 'doubt': 63,
 'science': 64,
 'payments': 65,
 '799': 66,
 'total': 67,
 'duration': 68,
 'months': 69,
 'learning': 70,
 'case': 71,
 'here': 72,
 'part': 73,
 'google': 74,
 'see': 75,
 'late': 76,
 'dashboard

In [ ]:
len(tokenizer.word_index)

270

In [ ]:
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

tokenized_sentence

[]

In [ ]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [ ]:
input_sequences

[[91, 1],
 [91, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 41],
 [11, 7, 1, 12, 41, 14],
 [11, 7, 1, 12, 41, 14, 51],
 [11, 7, 1, 12, 41, 14, 51, 64],
 [11, 7, 1, 12, 41, 14, 51, 64, 92],
 [11, 7, 1, 12, 41, 14, 51, 64, 92, 13],
 [11, 7, 1, 12, 41, 14, 51, 64, 92, 13, 145],
 [11, 7, 1, 12, 41, 14, 51, 64, 92, 13, 145, 146],
 [1, 12],
 [1, 12, 93],
 [1, 12, 93, 5],
 [1, 12, 93, 5, 42],
 [1, 12, 93, 5, 42, 29],
 [1, 12, 93, 5, 42, 29, 94],
 [1, 12, 93, 5, 42, 29, 94, 30],
 [1, 12, 93, 5, 42, 29, 94, 30, 2],
 [1, 12, 93, 5, 42, 29, 94, 30, 2, 8],
 [1, 12, 93, 5, 42, 29, 94, 30, 2, 8, 4],
 [1, 12, 93, 5, 42, 29, 94, 30, 2, 8, 4, 26],
 [1, 12, 93, 5, 42, 29, 94, 30, 2, 8, 4, 26, 42],
 [1, 12, 93, 5, 42, 29, 94, 30, 2, 8, 4, 26, 42, 65],
 [1, 12, 93, 5, 42, 29, 94, 30, 2, 8, 4, 26, 42, 65, 6],
 [1, 12, 93, 5, 42, 29, 94, 30, 2, 8, 4, 26, 42, 65, 6, 31],
 [1, 12, 93, 5, 42, 29, 94, 30, 2, 8, 4, 26, 42, 65, 6, 31, 66],
 [1, 12, 93, 5, 42, 29, 94, 30, 2, 8, 4, 26, 42, 65, 6

In [ ]:
max_len = max([len(x) for x in input_sequences])
max_len

32

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

padded_input_sequences

array([[  0,   0,   0, ...,   0,  91,   1],
       [  0,   0,   0, ...,  91,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 267,  18, 268],
       [  0,   0,   0, ...,  18, 268, 269],
       [  0,   0,   0, ..., 268, 269, 270]], dtype=int32)

In [ ]:
X = padded_input_sequences[ : , : -1]

y = padded_input_sequences[ : , -1]

In [ ]:
X

array([[  0,   0,   0, ...,   0,   0,  91],
       [  0,   0,   0, ...,   0,  91,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 267,  18],
       [  0,   0,   0, ..., 267,  18, 268],
       [  0,   0,   0, ...,  18, 268, 269]], dtype=int32)

In [ ]:
y

array([  1,  13,   7,   1,  12,  41,  14,  51,  64,  92,  13, 145, 146,
        12,  93,   5,  42,  29,  94,  30,   2,   8,   4,  26,  42,  65,
         6,  31,  66,  43,   7,   1,  67,  68,   6,   1,  12,  67,  68,
         6,   1,  12,   7,  52,  69,  32,   1,  67,  12,  41, 147,  66,
        52,  31,  53, 148,   7,   1,  95,   6,   1,  92,  13,   9,  19,
       149,   1, 150, 151, 152, 153,  14,  51,  64, 154,  14,  51,  64,
        14, 157,  70, 158,  97,  98,  10, 161,   1, 162,  95,  72,  99,
        70,  20, 100,  19,   5,  73,   6,  21,  13, 100,  20,  99,  70,
       163,  54,  44,   5,  73,   6,  21, 164, 165,  22,   3, 102,   5,
       103,  33,   9,   3,  45,   5, 104,   6,   1,  33,  15,  34,  16,
        54, 166,  32, 105,  22,   2, 102,   5,  33,   2,  10, 167, 168,
        20,  55,   1, 104,  10,   3, 169,   1, 106, 170,  21,  74, 172,
         4,  75,  43,  56,  43, 107, 173,   6,   1,  12,   7,   1, 107,
        68,   6,  15,   1, 103,  16,  15,   1,  16, 175, 108, 17

In [ ]:
X.shape

(834, 31)

In [ ]:
y.shape

(834,)

In [ ]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y,num_classes=283)


In [ ]:
y.shape

(834, 283)

In [ ]:
 from tensorflow.keras.models import Sequential
 from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()
model.add(Embedding(283, 100, input_length=31))
model.add(LSTM(150))
model.add(Dense(283, activation='softmax'))


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.build(input_shape = (None, 31))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

NameError: name 'model' is not defined

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 31, 100)             │          28,300 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 150)                 │         150,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 283)                 │          42,733 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 221,633 (865.75 KB)

 Trainable params: 221,633 (865.75 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.0556 - loss: 5.5632
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0926 - loss: 5.0569
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0737 - loss: 4.9522
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0943 - loss: 4.8950
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0760 - loss: 4.9152
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0849 - loss: 4.8380
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0979 - loss: 4.7010
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0981 - loss: 4.6438
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1331 - loss: 4.4490
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.1423 - loss: 4.2070
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.1937 - loss: 3.9870
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy:

In [ ]:
#import time
text = "mail"

# tokenize
token_text = tokenizer.texts_to_sequences([text])[0]
# padding
padded_token_text = pad_sequences([token_text], maxlen = 56, padding='pre')

print(padded_token_text)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0 57]]


In [ ]:
import numpy as np

# It will give 283 dimensional vector
model.predict(padded_token_text)

# it gives highest probability
np.argmax(model.predict(padded_token_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


110

In [ ]:
import time
text = "What if I miss a live"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
What if I miss a live session
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
What if I miss a live session will
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
What if I miss a live session will i
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
What if I miss a live session will i get
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
What if I miss a live session will i get a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
What if I miss a live session will i get a recording
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
What if I miss a live session will i get a recording of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
What if I miss a live session will i get a recording of the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
What if I miss a live session will i get a recording of the session
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
What if I miss a live session will i get a recording of the session you
